### ISSUE TITLE
please how to connect to rdp ?

### ISSUE THREAD

**Issue by titosalah** [RavensVenix/Free-RDP#2]
Hi bro

please help me how to connect from remote desktop app
error 
i use this data to connect
tcp.ngrok.io:11723
Username: administrator
Password: SayuLonte@

![2022-11-21_094117](https://user-images.githubusercontent.com/2828165/202993100-f3d2265d-6d8c-4746-8ec7-30f1a5365de7.jpg)

**Comment by RavensVenix** [comment]
you are doing it the wrong way

you didn't copy the whole ip
if the ip is like 0.tcp.ap.ngrok.io:666
then copy all the ip lines, don't cut any of the ip lines or you will fail the connection session

like how you forget the 1 digit behind it
